spring.application.name=clyvovet

# MySQL
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/clyvovet}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:clyvovet_fiap}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:clyvoVet@fiap2026}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html

# Server
server.port=8080